include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_single_quotes: ignore
    constant_identifier_names: ignore
    invalid_annotation_target: ignore
    invalid_use_of_protected_member: ignore
  plugins:
    - custom_lint

linter:
  rules:
    - sort_constructors_first
    - prefer_relative_imports
    - prefer_single_quotes